// ugo-uni-app/src/pages/index/index.vue
<template>
  <view :style="{height: pageHeight, overflow: 'hidden'}">
    <search @search="disableScroll" />
    <!-- 焦点图 -->
    <swiper class="banner" indicator-dots indicator-color="rgba(255, 255, 255, 0.6)" indicator-active-color="#fff">
      <swiper-item>
        <navigator url="/pages/goods/index">
          <image src="http://static.botue.com/ugo/uploads/banner1.png"></image>
        </navigator>
      </swiper-item>
      <swiper-item>
        <navigator url="/pages/goods/index">
          <image src="http://static.botue.com/ugo/uploads/banner2.png"></image>
        </navigator>
      </swiper-item>
      <swiper-item>
        <navigator url="/pages/goods/index">
          <image src="http://static.botue.com/ugo/uploads/banner3.png"></image>
        </navigator>
      </swiper-item>
    </swiper>
    <!-- 导航条 -->
    <view class="navs">
      <navigator open-type="switchTab" url="/pages/category/index">
        <image src="http://static.botue.com/ugo/uploads/icon_index_nav_4@2x.png"></image>
      </navigator>
      <navigator url="/pages/list/index">
        <image src="http://static.botue.com/ugo/uploads/icon_index_nav_3@2x.png"></image>
      </navigator>
      <navigator url="/pages/list/index">
        <image src="http://static.botue.com/ugo/uploads/icon_index_nav_2@2x.png"></image>
      </navigator>
      <navigator url="/pages/list/index">
        <image src="http://static.botue.com/ugo/uploads/icon_index_nav_1@2x.png"></image>
      </navigator>
    </view>
    <!-- 楼层 -->
    <view class="floors">
      <view class="floor">
        <view class="title">
          <image src="http://static.botue.com/ugo/uploads/pic_floor01_title.png"></image>
        </view>
        <view class="items">
          <navigator url="/pages/list/index">
            <image src="http://static.botue.com/ugo/uploads/pic_floor01_1@2x.png"></image>
          </navigator>
          <navigator url="/pages/list/index">
            <image src="http://static.botue.com/ugo/uploads/pic_floor01_2@2x.png"></image>
          </navigator>
          <navigator url="/pages/list/index">
            <image src="http://static.botue.com/ugo/uploads/pic_floor01_3@2x.png"></image>
          </navigator>
          <navigator url="/pages/list/index">
            <image src="http://static.botue.com/ugo/uploads/pic_floor01_4@2x.png"></image>
          </navigator>
          <navigator url="/pages/list/index">
            <image src="http://static.botue.com/ugo/uploads/pic_floor01_5@2x.png"></image>
          </navigator>
        </view>
      </view>
      <view class="floor">
        <view class="title">
          <image src="http://static.botue.com/ugo/uploads/pic_floor02_title.png"/>
        </view>
        <view class="items">
          <navigator url="/pages/list/index">
            <image src="http://static.botue.com/ugo/uploads/pic_floor02_1@2x.png"></image>
          </navigator>
          <navigator url="/pages/list/index">
            <image src="http://static.botue.com/ugo/uploads/pic_floor02_2@2x.png"></image>
          </navigator>
          <navigator url="/pages/list/index">
            <image src="http://static.botue.com/ugo/uploads/pic_floor02_3@2x.png"></image>
          </navigator>
          <navigator url="/pages/list/index">
            <image src="http://static.botue.com/ugo/uploads/pic_floor02_4@2x.png"></image>
          </navigator>
          <navigator url="/pages/list/index">
            <image src="http://static.botue.com/ugo/uploads/pic_floor02_5@2x.png"></image>
          </navigator>
        </view>
      </view>
      <view class="floor">
        <view class="title">
          <image src="http://static.botue.com/ugo/uploads/pic_floor03_title.png"></image>
        </view>
        <view class="items">
          <navigator url="/pages/list/index">
            <image src="http://static.botue.com/ugo/uploads/pic_floor03_1@2x.png"></image>
          </navigator>
          <navigator url="/pages/list/index">
            <image src="http://static.botue.com/ugo/uploads/pic_floor03_2@2x.png"></image>
          </navigator>
          <navigator url="/pages/list/index">
            <image src="http://static.botue.com/ugo/uploads/pic_floor03_3@2x.png"></image>
          </navigator>
          <navigator url="/pages/list/index">
            <image src="http://static.botue.com/ugo/uploads/pic_floor03_4@2x.png"></image>
          </navigator>
          <navigator url="/pages/list/index">
            <image src="http://static.botue.com/ugo/uploads/pic_floor03_5@2x.png"></image>
          </navigator>
        </view>
      </view>
    </view>
    <!-- 回到顶部 -->
    <view class="goTop icon-top"></view>
  </view>
</template>

<script>
  import search from '@/components/search';

  export default {

    data () {
      return {
        pageHeight: 'auto'
      }
    },

    components: {
      search
    },
    
    methods: {
      disableScroll (ev) {
        this.pageHeight = ev.pageHeight + 'px';
      }
    }
  }
</script>

<style scoped lang="scss">
  .banner {
    width: 100%;
    height: 340rpx;

    image {
      width: 100%;
      height: 340rpx;
    }
  }

  .navs {
    display: flex;
    justify-content: space-between;
    padding: 30rpx 44rpx;

    image {
      width: 128rpx;
      height: 140rpx;
    }
  }

  .floor {

    .title {
      width: 750rpx;
      height: 60rpx;
      padding: 20rpx 0 0 8rpx;
      background-color: #f4f4f4;
    }

    .items {
      padding: 20rpx 16rpx;
      overflow: hidden;

      navigator {
        width: 193rpx;
        height: 188rpx;
        margin-left: 10rpx;
        margin-bottom: 10rpx;
        float: left;
      }

      navigator:first-child {
        width: 232rpx;
        height: 386rpx;
        margin-left: 0rpx;
      }

      navigator:nth-child(2),
      navigator:nth-child(5) {
        width: 273rpx;
      }
    }

    &:first-child {

      .items {

        navigator {
          width: 233rpx;
        }
      }
    }
  }

  .goTop {
    position: fixed;
    bottom: 30rpx;
    /* #ifdef H5 */
    bottom: 65px;
    /* #endif */
    right: 30rpx;
  
    display: flex;
    justify-content: center;
    align-items: center;
    width: 100rpx;
    height: 100rpx;
    font-size: 48rpx;
    color: #666;
    border-radius: 50%;
    background-color: rgba(255, 255, 255, 0.8);
  }
</style>

// ugo-taro/src/pages/index/index.jsx
import Taro, { Component } from '@tarojs/taro'
import {
  View,
  Image,
  Navigator,
  Swiper,
  SwiperItem
} from '@tarojs/components'

import './index.scss'

import Search from '@/components/search'

export default class Index extends Component {

  config = {
    navigationBarTitleText: '首页'
  }

  constructor (props) {
    super(props)
    
    // 初始数据
    this.state = {
      pageHeight: 'auto'
    }
  
    // 绑定this指向
    this.disableScroll = this.disableScroll.bind(this)
  }

  disableScroll (ev) {
    // 阻止页面溢出产生滚动
    this.setState({
      pageHeight: ev.pageHeight
    })
  }

  componentWillMount () { }

  componentDidMount () { }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  render () {
    return (
      <View style={{overflow: 'hidden', height: this.state.pageHeight}}>
        {/* 搜索组件 */}
        <Search onSearch={this.disableScroll} />
        {/* 焦点图 */}
        <Swiper
          className="banner"
          indicatorDots
          autoplay
          circular
          indicatorActiveColor="#fff"
          indicatorColor="rgba(255, 255, 255, 0.6)">
          <SwiperItem>
            <Navigator url="/pages/goods/index">
              <Image
                className="image"
                src="http://static.botue.com/ugo/uploads/banner1.png"></Image>
            </Navigator>
          </SwiperItem>
          <SwiperItem>
            <Navigator url="/pages/goods/index">
              <Image
                className="image"
                src="http://static.botue.com/ugo/uploads/banner2.png"></Image>
            </Navigator>
          </SwiperItem>
          <SwiperItem>
            <Navigator url="/pages/goods/index">
              <Image
                className="image"
                src="http://static.botue.com/ugo/uploads/banner3.png"></Image>
            </Navigator>
          </SwiperItem>
        </Swiper>
        {/* 主导航 */}
        <View className="navs">
          <Navigator
            openType="switchTab"
            url="/pages/category/index">
            <Image
              className="image"
              src="http://static.botue.com/ugo/uploads/icon_index_nav_4@2x.png"></Image>
          </Navigator>
          <Navigator url="/pages/list/index/index">
            <Image
              className="image"
              src="http://static.botue.com/ugo/uploads/icon_index_nav_3@2x.png"></Image>
          </Navigator>
          <Navigator url="/pages/list/index">
            <Image
              className="image"
              src="http://static.botue.com/ugo/uploads/icon_index_nav_2@2x.png"></Image>
          </Navigator>
          <Navigator url="/pages/list/index">
            <Image
              className="image"
              src="http://static.botue.com/ugo/uploads/icon_index_nav_1@2x.png"></Image>
          </Navigator>
        </View>
        {/* 楼层 */}
        <View className="floors">
          <View className="floor">
            <View className="title">
              <Image
                className="image"
                src="http://static.botue.com/ugo/uploads/pic_floor01_title.png"></Image>
            </View>
            <View className="items">
              <Navigator className="navigator" url="/pages/list/index">
                <Image
                  className="image"
                  src="http://static.botue.com/ugo/uploads/pic_floor01_1@2x.png"></Image>
              </Navigator>
              <Navigator className="navigator" url="/pages/list/index">
                <Image
                  className="image"
                  src="http://static.botue.com/ugo/uploads/pic_floor01_2@2x.png"></Image>
              </Navigator>
              <Navigator className="navigator" url="/pages/list/index">
                <Image
                  className="image"
                  src="http://static.botue.com/ugo/uploads/pic_floor01_3@2x.png"></Image>
              </Navigator>
              <Navigator className="navigator" url="/pages/list/index">
                <Image
                  className="image"
                  src="http://static.botue.com/ugo/uploads/pic_floor01_4@2x.png"></Image>
              </Navigator>
              <Navigator className="navigator" url="/pages/list/index">
                <Image
                  className="image"
                  src="http://static.botue.com/ugo/uploads/pic_floor01_5@2x.png"></Image>
              </Navigator>
            </View>
          </View>
          <View className="floor">
            <View className="title">
              <Image
                className="image"
                src="http://static.botue.com/ugo/uploads/pic_floor02_title.png"></Image>
            </View>
            <View className="items">
              <Navigator className="navigator" url="/pages/list/index">
                <Image
                  className="image"
                  src="http://static.botue.com/ugo/uploads/pic_floor02_1@2x.png"></Image>
              </Navigator>
              <Navigator className="navigator" url="/pages/list/index">
                <Image
                  className="image"
                  src="http://static.botue.com/ugo/uploads/pic_floor02_2@2x.png"></Image>
              </Navigator>
              <Navigator className="navigator" url="/pages/list/index">
                <Image
                  className="image"
                  src="http://static.botue.com/ugo/uploads/pic_floor02_3@2x.png"></Image>
              </Navigator>
              <Navigator className="navigator" url="/pages/list/index">
                <Image
                  className="image"
                  src="http://static.botue.com/ugo/uploads/pic_floor02_4@2x.png"></Image>
              </Navigator>
              <Navigator className="navigator" url="/pages/list/index">
                <Image
                  className="image"
                  src="http://static.botue.com/ugo/uploads/pic_floor02_5@2x.png"></Image>
              </Navigator>
            </View>
          </View>
          <View className="floor">
            <View className="title">
              <Image
                className="image"
                src="http://static.botue.com/ugo/uploads/pic_floor03_title.png"></Image>
            </View>
            <View className="items">
              <Navigator className="navigator" url="/pages/list/index">
                <Image
                  className="image"
                  src="http://static.botue.com/ugo/uploads/pic_floor03_1@2x.png"></Image>
              </Navigator>
              <Navigator className="navigator" url="/pages/list/index">
                <Image
                  className="image"
                  src="http://static.botue.com/ugo/uploads/pic_floor03_2@2x.png"></Image>
              </Navigator>
              <Navigator className="navigator" url="/pages/list/index">
                <Image
                  className="image"
                  src="http://static.botue.com/ugo/uploads/pic_floor03_3@2x.png"></Image>
              </Navigator>
              <Navigator className="navigator" url="/pages/list/index">
                <Image
                  className="image"
                  src="http://static.botue.com/ugo/uploads/pic_floor03_4@2x.png"></Image>
              </Navigator>
              <Navigator className="navigator" url="/pages/list/index">
                <Image
                  className="image"
                  src="http://static.botue.com/ugo/uploads/pic_floor03_5@2x.png"></Image>
              </Navigator>
            </View>
          </View>
        </View>
        <View className="goTop icon-top"></View>
      </View>
    )
  }
}
